POST http://localhost:3000/irrigationEvent
Content-Type: application/json

{
  "content": {
    "name": "",
    "value": "on",
    "displayName": "Virtual Device",
    "deviceId": "42",
    "descriptionText": "",
    "unit": "",
    "type": "",
    "data": ""
  }
}