POST http://localhost:3000/irrigationEvent
Content-Type: application/json

{
  "content": {
    "name": "switch",
    "value": "on",
    "displayName": "Virtual Device",
    "deviceId": "42",
    "descriptionText": "Virtual Device: switch is on",
    "unit": null,
    "type": "digital",
    "data": null
  }
}